spring:
  application:
    name: delivery-api
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  file:
    name: delivery.log
  level:
    root: info
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'









