spring:
  application:
    name: delivery-api
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin123

